use_frameworks!

platform :ios, '10.0'

target 'YKTextField_Example' do
  pod 'YKTextField', :path => '../'

  target 'YKTextField_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
